version: 0.0
os: linux
files:
  - source: /html/index.html
    destination: /home/ec2-user/YOUR_PROJECT_DIR/html
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
  ApplicationStart:    
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user


